# Generated by Django 4.1.4 on 2023-05-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending')], max_length=20)),
            ],
        ),
    ]
